//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudDataGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientEmail { get; set; }
        public string ProjectType { get; set; }
        public int HourlyRate { get; set; }
        public string Description { get; set; }
        public bool Tos { get; set; }
        public bool Special { get; set; }
        public bool TermsAndService { get; internal set; }
    }
}
