//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudDataGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public int FacultyId { get; set; }
        public string FacultyName { get; set; }
        public string FacultyEmail { get; set; }
        public string Description { get; set; }
        public bool Tos { get; set; }
        public bool Special { get; set; }
    }
}
